### ISSUE TITLE
Area calculation failing for some elements pulled from Revit due to open curve error when curve is actually closed

### ISSUE THREAD

**Issue by enarhi** [BHoM/Revit_Toolkit#1008]
#### Description:
As per the title and the image below:
![image](https://user-images.githubusercontent.com/6752345/113224306-fcfd8480-923f-11eb-91a5-1422c7b4a6e4.png)

#### Steps to reproduce:
Certain elements pulled from Revit fail for area calculations due to perceived open curves that are actually closed. This appears to be specific to the method used for PlanarSurfaces. It goes away if the location is updated per a recreated surface from the edges derived from the failing surface as shown in the image above. On further inspection, this is due to tolerances and a gap between points of ~0.0004 per the Revit pull. Not sure the best fix for this, but it seems like one way or another the geometry pulled from revit can have small tolerance issues.

#### Expected behaviour:
Accurate area calculations on these elements as long as they are in fact defined by closed curves.

#### Test file(s):

[FailingAreaCalc.zip](https://github.com/BHoM/BHoM_Engine/files/6240069/FailingAreaCalc.zip)

**Comment by pawelbaran** [comment]
Well spotted edge case @enarhi! I think that source of the issue lies in tolerance: in Revit, the vertex tolerance is 0.000523ft, equal to 1.6e-4m, compared to 1e-6m default in BHoM. The value mentioned by you, ~0.0004m falls exactly in between the two values, causing the outline being treated as closed in Revit, but failing in BHoM.

I can think of two solutions to that, off the top of my head:
- look for gaps within the range above and fill them with line segments (the possibly remove the lines on Push, eh) - it sounds a bit dodgy to me as it will introduce super short segments for the only sake of making things not break
- try snapping the endpoints to remove the gaps - this sounds like asking for troubles as the curves will start moving, finding some intersections can be virtually impossible (think of two arc with a single intersection point) etc.

Following the above, I am not sure if that should be resolved on the Revit_Toolkit end tbh. Maybe a cleaner solution would be to remove the gaps downstream, after extracting from Revit. This would allow retaining full control by the user, very likely to confuse the newbies on the other hand.

What do you think?

**Comment by enarhi** [comment]
Interesting, that does make things a bit difficult. Could you apply rounding to the coordinates on the pull to force points to align, or does that also mess up arcs and the like? Given Revit modeling tolerances this still keeps us within acceptable tolerances of what's in Revit.

**Comment by pawelbaran** [comment]
Hmm, possibly - @LMarkowski do you think we could use `RoundCoordinates` in this case? If so, would that actually help, taken that the disjoint curve ends could be snapped to different points due to rounding?

**Comment by LMarkowski** [comment]
@pawelbaran @enarhi
Main issue with `RoundCoordinates` in it's current implementation for `PlanarSurface` is that it needs a normal of the object in the beginning. Which cannot be calculated if the curve is not closed. (Btw the method works exactly as the `IElement2D` one did before the recent changes - it might be good to align them.)

I'm not sure if I understand the matter correctly. Do we want to round the coordinates of all elements on the pull? Wouldn't it be a bit of an overkill? This issue seems to be more of an edge case.

Wouldn't an quick fix like this be a better solution instead?
![image](https://user-images.githubusercontent.com/48125514/113736014-0c2b7900-96fd-11eb-9f3a-2144f973ca65.png)
It seems it couldn't be done in a one step due to the lack of a public setter.

**Comment by pawelbaran** [comment]
We could round coordinates only of the elements that have open outlines. But still, my main concern is whether rounding would help at all: what if each end point of the disjoint curve gets rounded to different coordinates? Wouldn't that mean that the outline will keep being disjoint?

Regarding the normal query on `RoundCoordinates`, I have just raised https://github.com/BHoM/BHoM_Engine/issues/2441 to discuss the possible solution to that issue.

**Comment by LMarkowski** [comment]
> what if each end point of the disjoint curve gets rounded to different coordinates? Wouldn't that mean that the outline will keep being disjoint?

@pawelbaran, I mean.. I think of course it would remain disjoint. But it would be an edge case of an edge case. Two points, too close to each other to be picked up by the revit tolerance, but enough for our tolerance, and than been snapped to two different rounded coordinates :v 
I think we could also give a shot to pass the tolerance in the area methods, and maybe in such cases use Revit greater tolerance than our default 1e-6.

**Comment by pawelbaran** [comment]
Yeah, agreed about the edge case of an edge case. However, as we all know, occurrence of edge cases of edge cases is just a matter of time 😉 Passing other tolerance value to Area method could be an option, however not very intuitive to the user (plus, who knows where else will it break further downstream).

However, now when I think about it (again and again), since it is an edge case, wouldn't it be fine to simply add a line segment to fill the gap and raise a warning? Quoting myself:
> it sounds a bit dodgy to me as it will introduce super short segments for the only sake of making things not break

...but looking at the alternatives discussed above, maybe it should not be ruled out? Shall we vote? 😃

**Comment by pawelbaran** [comment]
@enarhi please note you may be able to kill two birds with one stone and get this one fixed while working on#1062 - using same tolerance on `Pull` and `Area` query should be a solution to the original problem. Or am I too optimistic?

**Comment by enarhi** [comment]
you are exactly right. Will confirm when testing #1062, but would expect that will close this as well.
