### ISSUE TITLE
Make the type not found error more informative

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#1013]
#### Description:

_"Element type has not been found for given BHoM Object."_

...could be something like:

_"Element type has not been found for given BHoM Object. Please make sure the name of the BHoM object (or its type property, e.g. Construction) is matching the Revit family type name."_

**Comment by JosefTaylor** [comment]
I had a shot at this in [my PR:](https://github.com/BHoM/Revit_Toolkit/pull/1023)
I think the big thing is letting the user know what the type is meant to be (i.e. the SectionProperty or relevant) so that they can go ahead and add it. Also, since this error pops up per-object, if the missing type is reported rather than the object GUID, Grasshopper will automatically combine the errors into one per missing type.
