### ISSUE TITLE
Revit_toolkit: Support to pull nested façade objects nested within curtain panels/grids/walls 

### ISSUE THREAD

**Issue by rboulton-BH** [BHoM/Revit_Toolkit#1026]
#### Description:

As discussed with @pawelbaran & @enarhi; we frequently receive architecture Revit models where the façade is comprised of nested (& sub-nested / façade-ception!) families and objects which are either difficult or impossible to Pull into BHoM. It would be great to have the capability to pull all nested objects and access them separately.

For example, I have a transparent glazed element I want to Pull directly to use in a thermal model but it is nested within a Window object within a Curtain Panel object so is basically inaccessible.

**Comment by enarhi** [comment]
One key part of this, converting native geometry of non-hosted wondows, nested or otherwise, will require further exploration. However the ability to pull a selected multiply nested window as described above currently fails completely due to the below code failing when hosts is null, and a tweak of this method will allow for the selected element(s) to at least come through as ModelInstances with location and parameter information.

![image](https://user-images.githubusercontent.com/6752345/117393075-2c8b5680-aea8-11eb-84aa-7d18241ecd0b.png)

**Comment by enarhi** [comment]
@pawelbaran expanding on this a bit, the only way we could pull geometry from scenarios like the one @rboulton-BH is dealing with is by adding support for extracting geometry from unhosted windows. As this is an edge case for now (only occurs when arch's use the generic model family saved as window category hack to enable it) I suggest we support primitive pulls for now to the fallback ModelInstance, with support for unhosted windows added if/when the amount of need for it justifies it. Thoughts?
