### ISSUE TITLE
Excel to Revit - Push GUID to shared parameter file

### ISSUE THREAD

**Issue by TZwielehner** [BHoM/Revit_Toolkit#1194]
When pushing parameter definition to Revit, the GUID is generated automatically, it seems. It is not equal to the BHoM_Guid; also, a costum property named "GUID" doesn't work.

Is there a way - and if not, can we add it - to assign a predefined GUID to the definition before pushing it?

**Comment by pawelbaran** [comment]
Thanks @TZwielehner for raising this. Could you please confirm that you want to push a shared parameter to Revit with a custom GUID? If so, it is impossible due to Revit API limitations I'm afraid. There is no way to set it on creation, and it is get only later on, as indicated in [Revit API Docs](https://www.revitapidocs.com/2018.2/50a62dcd-6027-9c69-377a-81fd96be88e8.htm). This makes sense from the programming point of view: GUIDs are usually generated by the software that owns the object, in this case Revit, and we have no control over it, unfortunately.

I will close this issue, assuming that the request is impossible to fulfil. However, if you know a manual way of changing the GUIDs, I would say we could give it a closer look whether this couldn't be mimicked with code. Otherwise, I am sorry, but we cannot do much about it 🙈
