### ISSUE TITLE
Issues with pulling from links in case of one document being linked multiple times

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#1477]
#### Description:

The issue occurs when a given document is linked multiple times, in either of scenarios:
- one document is linked multiple times to represent different (yet same) zones of the project
- one document representing same zone is linked multiple times due to nested linking

Currently none of the above is handled properly, which could probably be solved by tweaking `requestsByLinks` to work with `RevitLinkInstance` rather than `Document`:
https://github.com/BHoM/Revit_Toolkit/blob/4bea6f1dd3b939af1df433abd1f1e72146c43e8a/Revit_Core_Adapter/CRUD/Read.cs#L90-L103

**Comment by enarhi** [comment]
Adding that I have also seen this occur due to an Architect's link containing self reference to other architect links, and improperly saved so that those nested links are forced to appear when we link it without the option to not include nested links. This can be treated similarly to the first case you've listed.
