### ISSUE TITLE
Revit_Toolkit: Fix Push Rooflight

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#215]
Push Rooflight to Revit

**Comment by pawelbaran** [comment]
@michaldengusiak @ZiolkowskiJakub is this still relevant?

@FraserGreenroyd I am making you the only assignee - please feel free to pass the issue to a relevant person in your team, I will not be able to resolve it.

**Comment by FraserGreenroyd** [comment]
**By 30th November**

**Comment by pawelbaran** [comment]
After further investigation, it is impossible to make this work robustly because rooflights in BHoM are defined as surface-based objects of type `BH.oM.Physical.Elements.Window` attached to `BH.oM.Physical.Elements.Roof` - that is not compatible with Revit where rooflights are point-based family instances with predefined dimensions (they require family and family type name to instantiate).

The only sensible approach I see is to generate a default window family type with required outline on the fly. That is, however, complex to implement and not very practical on the user level. Instead, I believe it is better to use point-based `ModelInstances` that allow placing instances of chosen family types in given location. #953 has been raised in attempt to make realization of this workflow easier.
