### ISSUE TITLE
Revit_Toolkit: Cannot Load Family Symbol and Push FramingElement

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Revit_Toolkit#228]
Revit Family Library does not find Family Symbol for BHoMObject

**Comment by ZiolkowskiJakub** [comment]
Sample Files:
[Test Files.zip](https://github.com/BHoM/Revit_Toolkit/files/2806761/Test.Files.zip)

**Comment by jdarcyBHE** [comment]
[test.txt](https://github.com/BHoM/Revit_Toolkit/files/2807680/test.txt)

**Comment by ZiolkowskiJakub** [comment]
@jdarcyBHE any update on this? Can I close it?

**Comment by ZiolkowskiJakub** [comment]
@jdarcyBHE any update on this? Can somebody test it?

@IsakNaslundBh do you have any macro test which covers that?

**Comment by rolyhudson** [comment]
Not the dynamo or Grasshopper solution but this snippet I think shows the c# version
```
List<IObject> columns = new List<IObject>();
BH.oM.Geometry.Point basepoint = basepoint = BH.Engine.Geometry.Create.Point(-11, 3, 3);
BH.oM.Geometry.ShapeProfiles.CircleProfile profile = BH.Engine.Geometry.Create.CircleProfile(300);
BH.oM.Physical.Materials.Material material = BH.Engine.Physical.Create.Material();
BH.oM.Physical.FramingProperties.IFramingElementProperty props = BH.Engine.Physical.Create.ConstantFramingProperty(profile, material, Math.PI / 2);
BH.oM.Physical.Elements.Column column = BH.Engine.Physical.Create.Column(basepoint, 3.5, props);
column.Name = "col1";
column.CustomData.Add("Revit_familyName", "BHm_StructuralColumns_ConcreteRound");
column.CustomData.Add("Revit_familyTypeName", "300 Ø RC COL");
columns.Add(column);

RevitAdapter aRevitAdapter = new RevitAdapter(null, true);
List<IObject> result = aRevitAdapter.Push(columns);
```

I used the revit file here which has the family and family type used in the snippet: https://github.com/BHoM/samples/tree/release_2.2/Structural_Adapters/Interop%20Revit%20Robot%20ETABS

**Comment by rolyhudson** [comment]
And for a simple beam:
```
List<IObject> beams = new List<IObject>();
BH.oM.Geometry.Point start = BH.Engine.Geometry.Create.Point(-11, 3, 3);
BH.oM.Geometry.Point end = BH.Engine.Geometry.Create.Point(-11, 7, 3);
BH.oM.Geometry.ShapeProfiles.RectangleProfile profile = BH.Engine.Geometry.Create.RectangleProfile(0.4, 0.2, 0);
BH.oM.Physical.Materials.Material material = BH.Engine.Physical.Create.Material();
BH.oM.Physical.FramingProperties.IFramingElementProperty props = BH.Engine.Physical.Create.ConstantFramingProperty(profile, material, Math.PI / 2);
BH.oM.Geometry.Line beamCL = BH.Engine.Geometry.Create.Line(start, end);
BH.oM.Physical.Elements.Beam beam = BH.Engine.Physical.Create.Beam(beamCL,props);
            beam.Name = "beam1";

beam.CustomData.Add("Revit_familyName", "BHm_StructuralFraming_Concrete-RectangularBeam");
beam.CustomData.Add("Revit_familyTypeName", "300x500 DP RC BEAM");
beams.Add(beam);

RevitAdapter aRevitAdapter = new RevitAdapter(null, true);
List<IObject> result = aRevitAdapter.Push(beams);

**Comment by pawelbaran** [comment]
@ZiolkowskiJakub what is the status of this issue? Is it still relevant?

**Comment by FraserGreenroyd** [comment]
I am closing this issue as it has gone stale and there as been no new information nor reports of further problems. If anyone disagrees then please feel free to reopen (with additional information ideally to work with) :smile:

**Comment by markrocha** [comment]
All - learning this tool and it's an incredible piece of work! Just a note. I've been trying to recreate this issue and have found some issues. 

When I use the sample project RVT file that @rolyhudson described I'm able to push either steel or concrete columns. 

Below is example for concrete columns:
![image](https://user-images.githubusercontent.com/24485109/114774738-191c1e00-9d36-11eb-8546-c12cac998ab6.png)
![image](https://user-images.githubusercontent.com/24485109/114774769-2507e000-9d36-11eb-9f5c-1aadab6fe208.png)

Below is example for steel columns: 
![image](https://user-images.githubusercontent.com/24485109/114774886-4d8fda00-9d36-11eb-8ac9-62c905410999.png)
![image](https://user-images.githubusercontent.com/24485109/114774925-541e5180-9d36-11eb-9c4f-74ebc9a66fc8.png)

However, when I use a different revit project file, the behavior changes slightly - 

Below is example for concrete columns:
Works like a charm!
![image](https://user-images.githubusercontent.com/24485109/114775140-95aefc80-9d36-11eb-8a33-c7f212706b45.png)
![image](https://user-images.githubusercontent.com/24485109/114775234-b24b3480-9d36-11eb-9777-26b220cbbec1.png)

Below is example for steel columns:
I've tried both options discussed above by @ZiolkowskiJakub 
![image](https://user-images.githubusercontent.com/24485109/114775387-db6bc500-9d36-11eb-9dd5-27fb919a34bf.png)
![image](https://user-images.githubusercontent.com/24485109/114775444-ede5fe80-9d36-11eb-94f4-4b90ca30447a.png)
![image](https://user-images.githubusercontent.com/24485109/114775534-06561900-9d37-11eb-8709-6d0e9715a53d.png)

Any ideas? I've gone through the Revit families to determine if a Revit family setting is the root cause of the issue. No luck - Thanks in advance!

**Comment by markrocha** [comment]
I was running BHOM 4.0 beta and just upgraded to 4.1 Beta. Just ran it again and it worked! 

![image](https://user-images.githubusercontent.com/24485109/114886642-5384ca00-9dcd-11eb-85e3-3939052b5a21.png)
![image](https://user-images.githubusercontent.com/24485109/114886699-60092280-9dcd-11eb-8658-77e9a902e434.png)

**Comment by pawelbaran** [comment]
Hi @markrocha! It is great to hear that you like what we are building here 😃 From what I know (and what we have tested), this functionality (name matching of family type on Push) is working fine since a few releases, with full robustness being achieved after the final tweaks that were made in 4.1.

I am happy that your issue disappeared after switching from 4.0 to 4.1, likely it was of the cases that have been fixed recently - however, please shout out in case it reoccurs, I will gladly look into this and help.

If you enjoy testing other opportunities provided by BHoM, I would recommend trying [FamilyLibrary](https://github.com/BHoM/Revit_Toolkit/wiki/FamilyLibrary) as an easy way to automate loading of the families.

Also, please do not hesitate to raise new issues with questions/bugs/feature requests if you find anything that you think could be improved. Thanks and have fun with BHoM! 🤖

**Comment by markrocha** [comment]
Awesome thanks! I will check out that Family mapper! Appreciate the response. I'll continue to post / comment new issues to learn more
