### ISSUE TITLE
Revit_Toolkit: Framing element incorrect property naming

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Revit_Toolkit#232]
Just notices that framing elements sue the bar naming for rotation angles:
![image](https://user-images.githubusercontent.com/34092831/52049007-9b004200-2544-11e9-82cd-36be4d2d896f.png)
This should actually be 'Cross-Section Rotation'

Work around is to add the information as 'Cross-Section Rotation' within custom data

**Comment by ZiolkowskiJakub** [comment]
Hi @jdarcyBHE ,

It seems it suppose to be as you described:


Looking ate the code:
```
            oM.Structure.Properties.Framing.ConstantFramingElementProperty barProperty = framingElement.Property as oM.Structure.Properties.Framing.ConstantFramingElementProperty;
            if (barProperty != null)
            {
                double orientationAngle = (Math.PI * 0.5 - barProperty.OrientationAngle) % (2 * Math.PI);
                Parameter rotation = aFamilyInstance.LookupParameter("Cross-Section Rotation");
                rotation.Set(orientationAngle);
            }
```

Can you attached the sample where the issue is shown?

You can save it [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue232-FramingElementIncorrectPropertyNaming?csf=1&e=d2pcfB) or attach to this issue

Thanks in advance

**Comment by ZiolkowskiJakub** [comment]
Hi @jdarcyBHE,

Any update on that or can I close this issue?

**Comment by jdarcyBHE** [comment]
Jakub, this still seems to be an issue sample file saved in the link you posted.

**Comment by ZiolkowskiJakub** [comment]
Hi @jdarcyBHE,

There were couple changes made @IsakNaslundBh. Can you please check if you still have this issue?

**Comment by jdarcyBHE** [comment]
Correct, this has been addressed in the latest updates.
