### ISSUE TITLE
Revit_Toolkit: Issues With Pulling PanelPlanars With Curved Outlines

### ISSUE THREAD

**Issue by enarhi** [BHoM/Revit_Toolkit#236]
Floors with curved outlines are returning some issues. Example 1 shown below, where the arc has been defined with what appears to be the wrong domain, leading to a disconnected external edge that leads to a failed slab. Looks like the domain is the correct length, but has the wrong start value throwing it off. This has been occurring in most locations where arcs are part of the floor outline, as shown below in the additional images.

![image](https://user-images.githubusercontent.com/6752345/52311804-202c9200-295d-11e9-9630-66b892d2d3a9.png)

Additional Examples:
![image](https://user-images.githubusercontent.com/6752345/52311887-6da8ff00-295d-11e9-82ef-50cdba449f3c.png)

![image](https://user-images.githubusercontent.com/6752345/52311932-9a5d1680-295d-11e9-8537-324190588e55.png)

![image](https://user-images.githubusercontent.com/6752345/52311974-bbbe0280-295d-11e9-89f3-9e3346bf4769.png)

**Comment by ZiolkowskiJakub** [comment]
Hi @enarhi,

I strongly believe this issue is related to fact the Panels are pulled from Revit Structural Analytic model. We are currently working on new approach where Walls, Floors, Roofs can be pulled as Architectural (or I could say Physical) objects ([BHoM PR](https://github.com/BHoM/BHoM/pull/418)). This hopefully allows you to pull physical geometry and use it to create BHoM Analytical Panels.

I hope that will helps!

**Comment by pawelbaran** [comment]
@enarhi any chance to replicate this issue after such a long time? I am just bugfixing the Pull of analytical elements, glad to resolve this one if possible.

**Comment by enarhi** [comment]
@pawelbaran working as expected now, curved floors are coming through beautifully. Closing this one.
