### ISSUE TITLE
Revit_Toolkit: Setting Revit parameter

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Revit_Toolkit#275]
Currently you are able to push objects and any BHoM parameter that has a matching Revit Parameter is then updated, I believe this only/predominately works with text values. If this is able to be expand to allow a compatible BHOM parameter to be applied to any Revit parameter we will be able to fully control objects in Revit without having to had specific code written for each object parameter.

.i.e assigning constraint levels for walls, pushing a object with the base or top constraint in customdata set to a BHoM level object.

**Comment by ZiolkowskiJakub** [comment]
Hi @jdarcyBHE,

Thank you very much for your query.

I am not sure if I properly understand what you are trying to achieve but it is possible to set up any (excluding ReadOnly) parameter in Revit via CustomData. Here is example how to set up Base Constraint (ElementId parameter) and Unconnected Height (Double parameter) using BHoM:

![image](https://user-images.githubusercontent.com/16777757/58474944-727c0380-8144-11e9-8845-af46496e89e9.png)

Just keep in mind there are four base storage types for parameters:
1. ElementId
2. Double
3. Integer
4. String

You need to be careful when setting parameters in CustomData to match with storage type of parameter you want to setup. 

In sample above you cannot assign Base Constraint parameter using Level Name or Unconnected Height using string.

You do not have to pull Element before setting the element parameter. If you know ElementId of  Element you want to update then you can create BHoMObject with specific ElementId and set of CustomData parameters you want to update:
![image](https://user-images.githubusercontent.com/16777757/58475843-f46d2c00-8146-11e9-8506-2e8b8587662c.png)


Both samples saved here:
[Sample](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue275-SettingRevitParameter?csf=1&e=GQsRmY)

Please let me know if you have any questions. Please close this issue if this solves your query.

Thank you.

**Comment by ZiolkowskiJakub** [comment]
This pull request shall be closed according to discussion with @jdarcyBHE 

**Summary: Revit Parameters which store ElementIds cannot be set by providing Element name.**

Example:
Base Constraint parameter of wall stores ElementId of Level and it cannot be set by providing Level Name. You need to extract Level ElementId and set it as value of Base Constraint parameter.

It is very difficult to implement the functionality that allows setting ElementId parameter by providing its name. This is due to fact in most of the cases it would not be one to one relation and ElementId does not determine what kind of object can be assign to parameter.
