### ISSUE TITLE
Revit_Toolkit: set up and configure references for Release builds

### ISSUE THREAD

**Issue by alelom** [BHoM/Revit_Toolkit#347]
#### Description:
When setting up the `Release` build in the Revit_Toolkit:
<img src="https://user-images.githubusercontent.com/6352844/60892384-00c0ca80-a257-11e9-9161-8ffc3a7f5a26.png" width=300>

you get the following missing references: 
- Project `Engine_Revit_UI`
     * `Reflection_oM`
     * `RevitAPI`
     * `RevitAPIIFC`
    * `RevitAPIUI`

- Projects `Adapter_Revit_UI`, `Revit_UI` and `Revit_Test`
    * `RevitAPIUI`
     * `RevitAPI`

EDIT:
As explained in @ZiolkowskiJakub [comment below](https://github.com/BHoM/Revit_Toolkit/issues/347#issuecomment-509955752) this is because
>you need to specify for which version of Revit you want to build Revit_Toolkit for. Therefore we should setup following Configurations:
`Release2018`
`Release2019`
> 
> Of course we could also provide default settings `Release` configuration but the question is what is default Revit version for Revit_Toolkit?
> 
> We need to keep in mind that there could be the cases when method works fine and run through Macro test with with no errors for Revit_Toolkit `Release2018` configuration but may return errors for `Release2019` and vice-versa.

**Comment by alelom** [comment]
Lowered importance as I thought it was preventing me to correctly build the installer; instead that was linked to another issue.

**Comment by ZiolkowskiJakub** [comment]
Hi @alelom 

I would not classify this issue as a bug. This is intentional behaviour due to fact you need to specify for which version of Revit you want to build Revit_Toolkit for. Therefore we should setup following Configurations:
`Release2018`
`Release2019`

Of course we could also provide default settings `Release` configuration but the question is what is default Revit version for Revit_Toolkit?

We need to keep in mind that there could be the cases when method works fine and run through Macro test with with no errors for Revit_Toolkit `Release2018` configuration but may return errors for `Release2019` and vice-versa.

**Comment by alelom** [comment]
Thank you for your answer @ZiolkowskiJakub .
My bad, I had incorrectly identified this with an issue that prevented the compiling of the installer for a certain build.
I agree, this can be switched to `compliance` instead of `bug`, and perhaps the title changed. I'll give it a go, feel free to modify it.

**Comment by FraserGreenroyd** [comment]
I would say this might be linked to #350 which is doing away with version specific DLLs (while still working for both 2018 and 2019 versions of Revit) - so we might be able to do away with different configurations and go back to just `Debug` and `Release` possibly.
