### ISSUE TITLE
Revit_Toolkit: fix Flip on pull Walls

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#371]
#### Description:

As discussed,  Get consistent `Flip` of the `wall` for different physical pulling method from Revit

**Comment by pawelbaran** [comment]
@michaldengusiak @ZiolkowskiJakub @FraserGreenroyd is this issue still relevant?

**Comment by michaldengusiak** [comment]
Sure 100% still need solving

**Comment by pawelbaran** [comment]
@FraserGreenroyd I am making you the only assignee - please feel free to pass the issue to a relevant person in your team, I will not be able to resolve it.

**Comment by FraserGreenroyd** [comment]
To be left for next milestone 3.1 after discussion with @rboulton-BH considering other current priorities.

**Comment by FraserGreenroyd** [comment]
Owing to the lack of test file, and the methods for fixing normals now existing within the core engines since this issue was raised, and the lack of issue reported by other people in the interim period, I am considering this a non-issue for the time being. If this is an issue for anyone please feel free to reopen with an adequate test file to support :smile:
