### ISSUE TITLE
Pull physical walls not working

### ISSUE THREAD

**Issue by rwemay** [BHoM/Revit_Toolkit#372]
#### Description:

See test file and script. 

#### How to replicate:

See test file and script. 

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Issues/Issue-372_Pull%20Physical%20Walls%20Bug?csf=1&e=doubJk

**Comment by ZiolkowskiJakub** [comment]
Hi @rwemay,

I investigated this issue and it seems walls information is converted correctly to BHoM but the issue is related to Revit prompts showing during the pull... 

You probably have not been patient enough to click hundred times "Cancel" over all the prompts :-)

The reason for prompt is Revit_Toolkit needs to **TEMPORARY** modify document (transaction with the changes is rolled back after the changes) to get all necessary information for Wall convert method. I will add additional code to suppress unnecessary messages.

As far as I know similar issue has been reported here: #358
