### ISSUE TITLE
Revit_Toolkit: StructuralUsage type "bracing" error

### ISSUE THREAD

**Issue by JonathanNillius** [BHoM/Revit_Toolkit#485]
#### Description:
When pushing 1D elements to revit with structural usage bracing geometry appears to snap to nearby centrelines. 

#### How to replicate:
use testfile

#### Expected behaviour:
Centreline matches grasshopper script locations. 

#### Picture:
![image](https://user-images.githubusercontent.com/54712802/70449376-c5daf100-1a99-11ea-9cc8-23b6f67deedf.png)
Selected elements pushed as bracing and incorrectly snapped to bottom chord. 

#### Test file(s):
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue485

**Comment by rwemay** [comment]
Assuming this issue is related to bracing system families, as an aside, there are reasons for/against using the 'bracing' system family type in Revit, but I personally avoid them. Bracing are defined by their connection to (and position along) adjacent elements, as such they can tend to snap to odd positions depending on what they are connecting to. I typically try to use beam elements, and set the geometry/positions with more control. The downside is that they aren't treated as 'bracing' in the model, which has helpful advantages like showing up dotted lines/symbols in plan to indicate vertical braced bays.

**Comment by pawelbaran** [comment]
@JonathanNillius I have just ran the test script and seems that the issue has been resolved with #751:

![image](https://user-images.githubusercontent.com/26874773/84799284-5a4f7e80-affc-11ea-909d-b5f40f9fe526.png)

I am closing this issue, please feel free to reopen in case it reoccurs.
