### ISSUE TITLE
Revit_Toolkit: ToBHoMEnvironmentPanel seems to contain a lot of boilerplate

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#541]
#### Decription:
Each of the methods with the name as in the title seems to contain some 80-90% of repeated code.

**Comment by pawelbaran** [comment]
@FraserGreenroyd please feel free to assign a more appropriate person to this one if you believe it should be someone else

**Comment by FraserGreenroyd** [comment]
On review, I'm not sure if it can be simplified. It doesn't appear to contain boilerplate so much as repetitive tasks but have to use specific data from each object which can be converted from Revit to an Environment Panel.

I would say the best way to solve the length of the file would be either to refactor to a core method that the individual methods call, or to remove all of the `UpdateValues` option on the fragments and then refactor from there.

On the basis of the original issue I am closing with this comment because it does not seem to contain much boilerplate, but may be worth tidying up in the future once map settings work is fully finished.
