### ISSUE TITLE
Revit_Toolkit: Element z-justification

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Revit_Toolkit#622]
#### Description:
This might be a well known bug/behaviour, but I couldn't find any issues about it.

The location of IFramingElement/Bar after being pulled does not correspond properly with their location in Revit.

Specificly z-justification
but also noticed that end extension was not used,

Now these thing are placed on the custom data after the pull, but it's not very useful unless you're pushing back to Revit again(?)

This is probably a feature request, but you'll know best @pawelbaran 

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/EvT8YPLsFNtMu0GhOSQqZFMB69dmZcVvQll1v_3iXA0S7A?e=ultinw

**Comment by pawelbaran** [comment]
Thanks @kThorsager for flagging this up. This problem is related to the fact that Physical `IFramingElements` do not have offset/justification properties, therefore on pull their location curves get moved to represent alignments. This processing, however, cannot be easily reverted on Push. Atm it is a mess that grew in complexity in the last year or so, when I was trying to capture the issue, without success.

I am going to put a clear structure into this problem in the coming milestone - it is one of my key priorities.

**Comment by kThorsager** [comment]
Yes, very understandable 
Will highlight that pulling as `Bar` behaves similarly (and they do have a `Offset`)

**Comment by pawelbaran** [comment]
This was a long discussion with @IsakNaslundBh - we decided to leave the decision about analytical offset to the engineer as it might be dangerous (please correct me if I am wrong).

In general, this problem needs to be mapped out properly - I will keep you both posted on that once I start digging.
