### ISSUE TITLE
Revit_Toolkit: Implement PullRepresentationConfig

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Revit_Toolkit#681]
#### Description:

Currently [`RevitPullConfig`](https://github.com/BHoM/Revit_Toolkit/blob/master/Revit_oM/Config/RevitPullConfig.cs) has three properties `PullEdges`, `PullSurfaces` and `IncludeNonVisible`. Since we are thinking of adding ability to pull mesh representations (#680), it would be good to wrap all these into a separate type that would become a property of `RevitPullConfig`:
- class name: `PullRepresentationConfig`
- properties:
    - `PullEdges`
    - `PullSurfaces`
    - `PullMeshes`
    - `IncludeNonVisible`
    - `DetailLevel` - to wrap [`ViewDetailLevel`](https://www.revitapidocs.com/2020/1f75aa53-ca98-df48-3286-a06b56096054.htm) and drive the value of [`levelOfDetail`](https://www.revitapidocs.com/2020/b571177c-1268-35cd-0be1-e19db29fcb20.htm), where lowest detail level will impose `levelOfDetail == 0` and highest `levelOfDetail == 1`.

@al-fisher @rwemay @alelom please feel free to comment/adjust

**Comment by rwemay** [comment]
I think 'PullGeometry' is more intuitive. Do we need PullSurfaces aswell as PullEdges? Why not just Geometry and the object geometry (whatever it is) is returned. If someone wants edges, they can just explode the geometry.

**Comment by pawelbaran** [comment]
I hesitated over _PullGeometryConfig_ too, but not sure if we do not want to expand it to e.g. textual representation, as discussed with @al-fisher and @alelom (this, however, seems not to be applicable to Revit). After a second thought I would tend to rename to _PullGeometryConfig_ actually, thanks!

Keeping all three pull geometry Booleans is considered for two reasons:
- pulling curves should be more lightweight than pulling e.g. meshes
- `PullSurfaces` will be limited to `PlanarSurfaces` for now, while `PullEdges` can pull virtually any curve, incl. nurbs

Another thing that had just came to my mind: wouldn't it be worth introducing `RevitGeometryFragment` to store the outputs of geometry pull?

**Comment by rwemay** [comment]
Yes definitely on Fragment (although I don't think you need Fragment in the title). Keep all the geometry together. I suppose the other question is: will anyone want to pull surfaces, edges and meshes simultaneously? Probably not advised, so maybe it's a PullGeometryConfig, then options on what to pull. I think that's what you're intending anyway?

**Comment by pawelbaran** [comment]
By options, do you mean an `enum`? This could be the way to go, instead of three Booleans. Then we would have `PullGeometryConfig` type with three properties:
- `enum RevitGeometryRepresentation { None, Edges, Surfaces, Meshes }` - I hate the name, waiting for better candidates 🤣 
- `bool IncludeNonVisible`
- `enum DetailLevel { Coarse, Medium, Fine }`

**Comment by alelom** [comment]
Great thinking @pawelbaran ! Some thoughs on my side (just as suggestion/personal opinions, open to discussion!

### Name of the "config"
I'd consider dropping the `Pull` part from `PullGeometryConfig`. Reasons:

- Mainly, prefix `Pull` is redundant as this will be an input to a `PullConfig`
- Secondarily, I think this config class should be considered abstract from Push/Pull; in case you want to push a the geometrical representation of some objects, you will be able to use the same class `[...]Config`

Further, for the second part of the name `PullGeometryConfig`, I'd consider swapping `Geometry` for `Representation`, for the same reasons discussed in the various calls on "Representation". See the last paragraph called "Further Phases" in https://github.com/BHoM/BHoM_Engine/issues/1694. 
Summarising, I think that using "geometry" instead of "representation" might initially be more intuitive, but on the long term we want to move away from that and formalise the representation concept better as part of the framework. You might want to Pull a different representation out, something that does not have to be Geometry in all cases.

To conclude, I'd propose `RepresentationConfig`.  

Later when we define a common interface this could become `RevitRepresentationConfig` and the latter moved up in the base BHoM_oM as an interface called `IRepresentationConfig`.

### The "options"
> By options, do you mean an `enum`? 

Sounds like a good idea to me.

> * `enum RevitGeometryRepresentation { None, Edges, Surfaces, Meshes }` - I hate the name, waiting for better candidates 🤣

I think we should consider more the namespaces when defining names. It will be under the Revit namespace, so I'd simply drop Revit.  
`GeometryRepresentation` sounds good. It specifies that the Representation you are talking of is of geometrical type. Could be `GeometricalRepresentation`, no preference there.

**Comment by pawelbaran** [comment]
Thanks @alelom for the detailed answer, please see my comments below.

### Name of the "config"
> I'd consider dropping the `Pull` part from `PullGeometryConfig`

Yes and no. Some parts of the config will be pull-specific. Like `IncludeNonVisible` or `DetailLevel` - they seem to be a one-way (from Revit) setting. Or am I looking too narrow?

> To conclude, I'd propose `RepresentationConfig`.

This might be a good idea on framework level, but I am afraid this will be meaningless for the end user - geometry is geometry for some 99.9% of the users (who, in the end, should be the ones we are making happy). I would like to keep it intuitive at the first place.

> Later when we define a common interface this could become `RevitRepresentationConfig` and the latter moved up in the base BHoM_oM as an interface called `IRepresentationConfig`.

That I am fine with: `PullGeometryConfig` (or `GeometryConfig`, depending on what we decide upon) can still inherit from `IRepresentationConfig`, keeping it neat in the big picture.

### The "options"
> I think we should consider more the namespaces when defining names. It will be under the Revit namespace, so I'd simply drop Revit.

Not sure about that - again, 99.9% of the users does not know what namespace is, and it is them who are meant to use it (and understand). However - is this enum something you would want to move to the Adapter at some point? Then happy to drop _Revit_ prefix as it will be gone at some point anyways.

> `GeometryRepresentation` sounds good. It specifies that the Representation you are talking of is of geometrical type. Could be `GeometricalRepresentation`, no preference there.

Possibly a good point (especially with regard to UI browsability _geometrical_ vs _geometry_), let's see what others think.

**Comment by al-fisher** [comment]
> will anyone want to pull surfaces, edges and meshes simultaneously? 

I can imagine a workflow where someone wants to pull _both_ a line representation in order to do model laundry and manipulate. Whilst simultaneously pulling a mesh for a render preview. or indeed overlay the two 
(the geometries will obviously be a high risk of getting out of sync - so fragment is right approach)

That all said - as we implement more and more explicit converts - you will not be relying on this config for the geometry used in an IElement for example.

So `enum` right now is prob best simple solution to avoid loads of toggles 😄

**Comment by pawelbaran** [comment]
Oke, `enum` named `GeometricalRepresentation` it is :D

Now looking at my answer to @alelom's comments again, I think I would go for `RevitRepresentationConfig` because:
- adapter's `ActionConfig` will at some point gain a property named `RepresentationConfig` that will show in the UI also for `RevitPullConfig`
- common `RevitRepresentationConfig` for both push and pull should be desirable in long term, as we might want to push only visible parts of the BHoM objects to Revit at some point, same as we want to pull now

Then, as in my previous comment, I would think of moving `GeometricalRepresentation` enum to BHoM_Adapter - how does that sound @alelom?

**Comment by pawelbaran** [comment]
Zooming out, I would say this is the right moment to prototype it on BHoM_Adapter level before we implement a software-specific solution.

**Comment by rwemay** [comment]
@al-fisher , on pulling multiple geometric representations, you'd get that anyway in the Revit environment, as you get a 'location' and lots of other bits. Also if someone wants to pull different representations they can always to two queries. Don't forget the memory if people pull edges + pull surfaces + pull meshes for large models. The model I pulled all edges on I showed you the other day took about half an hour (just edges) and was not a massive model. 

I think great idea to put this adapter side, especially if we're going with the more generic and broad RepresentationConfig. I wouldn't underestimate the expectation to see 'geometry' on the UI side though. Perhaps Representation is an interface that Geometry and others in the Representation namespace implement, in any case needs to be prominent within the representation set up.

**Comment by alelom** [comment]
> Then, as in my previous comment, I would think of moving `GeometricalRepresentation` enum to BHoM_Adapter - how does that sound @alelom?

BHoM_Adapter is not the place for this I'd say.
With @al-fisher we were considering the creation of a new `Representation_oM` for these things.

**Comment by pawelbaran** [comment]
Sounds like this topic is quickly growing in scope. What do you guys think about a focus session next week to map it out? I would feel much more comfortable making sure that we have architecture set up before I start implementing repo-specific content.

**Comment by rwemay** [comment]
I think it's very worth it @pawelbaran . I think it will be a relatively quick/simple one, but valuable as will be used across several TK's later.

**Comment by al-fisher** [comment]
Thanks @pawelbaran - yep let's try and grab a focused chat on this tomorrow.
