### ISSUE TITLE
Floors with openings occasionally come through as multiple floors, sometimes with external edge errors

### ISSUE THREAD

**Issue by enarhi** [BHoM/Revit_Toolkit#754]
#### Description:
Some Revit floors with openings come pulled as multiple floors with no openings, as per below.
![image](https://user-images.githubusercontent.com/6752345/84953543-8fb1a600-b0a8-11ea-8aff-c1abc22625ef.png)
![image](https://user-images.githubusercontent.com/6752345/84953585-a5bf6680-b0a8-11ea-8148-933a271581bb.png)
![image](https://user-images.githubusercontent.com/6752345/84953206-f84c5300-b0a7-11ea-937c-8b72568eaa34.png)

#### Steps to reproduce:
See test script below, this seems especially common when using floor objects after pulling them from Revit (Revit test file included below as well).

#### Expected behaviour:
These objects should not have the external edges open error, should be a single floor with openings, and SolidVolume() etc should work with the resulting object.

#### Test file(s):
[FloorPullTest.zip](https://github.com/BHoM/Revit_Toolkit/files/4795240/FloorPullTest.zip)

**Comment by pawelbaran** [comment]
@enarhi I've used your test file, but appartently the openings are gone due to the reduction of the model:
![enarhi](https://user-images.githubusercontent.com/26874773/87164205-ca35e980-c2c8-11ea-896c-08f33c1a5127.png)

However, I think your issue should be resolved with https://github.com/BHoM/Revit_Toolkit/pull/796. To test it, I've introduced a few random openings, all of the coming out as expected:
![enarhi3](https://user-images.githubusercontent.com/26874773/87164496-1f71fb00-c2c9-11ea-83b0-9e00ef195e40.png)

Would be nice if you could review the PR mentioned above to make sure that your issue is resolved.

**Comment by enarhi** [comment]
@pawelbaran looks like I included the wrong test file, but in spite of that, will test on that pr with the problem one!
