### ISSUE TITLE
Revit_Toolkit: Ceiling Patterns Pulling Incorrectly

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Revit_Toolkit#896]
#### Description:
The ceiling object's pattern that's pulled is off in the X and Y directions:

![image](https://user-images.githubusercontent.com/34316256/98259698-6e1a6380-1f50-11eb-9292-0ddbc9454a99.png)

**Comment by FraserGreenroyd** [comment]
@kayleighhoude following an investigation by myself, @michaelhoehn , and @pawelbaran  we have determined that this is a limitation of Revit, and not the BHoM conversion of a Ceiling Pattern.

From investigation of the Revit API, and how Revit is handling Ceiling Patterns, it is a 2D textured image projected onto a 3D model. This projection is handled by Revit and is decided by how Revit opts to draw the pattern on the object. The BHoM takes the data from the UV projection and calculates the most appropriate pattern for the ceiling from that. However, Revit API does not appear to provide the necessary data for us to map what Revit is visualising vs what Revit is telling us.

@michaelhoehn , @pawelbaran , and I have spent significant time attempting to see if we can pull the lines from the pattern as other objects (e.g. model instances) with no success. At this stage, the evidence points towards this being a Revit issue, rather than a BHoM one. Unless significant new information is able to come to light, either in a different API call, or how the 2D information can map to the 3D, I do not feel we will be able to successfully reproduce a Revit picture onto BHoM geometry.

I feel we have exhausted our capacity to resolve this. I welcome others to try and provide insight or code, the files which handle the patterns are XYZ and ABC, but unless information comes in by the end of the milestone, I think this issue will have to be closed as a can-not-fix 😞

**Comment by pawelbaran** [comment]
I need to correct @FraserGreenroyd in one point: 2D ceiling pattern can be manipulated in Revit (one can drag the lines and adjust it), but the information about such shift is not available through the API (or at least I could not find the way to extract it 🙊). So I agree with the conclusion above, I am afraid this issue is one of the can-not-fix crowd 😢
